[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
english = { path = "../english" }
hex = "0.4.3"
itertools = "0.10.3"
rayon = "1.6.0"
transpose = "0.2.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
